# ixDROP - config #

 #Tu ustaw itemy które mają być w gui (dropped)
  item1: diamond
  item2: iron
  item3: gold
  item4: apple
  item5: book
  item6: air # Nic
 #Nazwa itemu powyżej np (n1 = &bDiament)
  name1: &3DIAMENT
  name2: &7ZELAZO
  name3: &eZLOTO
  name4: &cJABLKO
  name5: &6KSIAZKA
  name6: &lNIC
 #Chance = Szansa (pamietaj o wstawianu 2 x %)
  chance1: 10%%
  chance2: 10%%
  chance3: 10%%
  chance4: 10%%
  chance5: 10%%
  chance6: 10%%
 #Lore = Opis itemku (Nowa linijka = ||)
  lore1:&8•  &7Szansa: &6%{chance1}%||&8• &6Status: %{drop.%{item1}%.%player%}%||&8• &aFORTUNE: &cWYLACZONE
  lore2:&8•  &7Szansa: &6%{chance2}%||&8• &6Status: %{drop.%{item2}%.%player%}%||&8• &aFORTUNE: &cWYLACZONE
  lore3:&8•  &7Szansa: &6%{chance3}%||&8• &6Status: %{drop.%{item3}%.%player%}%||&8• &aFORTUNE: &cWYLACZONE
  lore4:&8•  &7Szansa: &6%{chance4}%||&8• &6Status: %{drop.%{item4}%.%player%}%||&8• &aFORTUNE: &cWYLACZONE
  lore5:&8•  &7Szansa: &6%{chance5}%||&8• &6Status: %{drop.%{item5}%.%player%}%||&8• &aFORTUNE: &cWYLACZONE
  lore6:&8•  &7Szansa: &6%{chance6}%||&8• &6Status: %{drop.%{item6}%.%player%}%||&8• &aFORTUNE: &CWYLACZONE
  # msg = Wiadomosc po wykopaniu surowca
  msg1: &6Znalazles %{name1}% &7(x1)
  msg2: &6Znalazles %{name2}% &7(x1)
  msg3: &6Znalazles %{name3}% &7(x1)
  msg4: &6Znalazles %{name4}% &7(x1)
  msg5: &6Znalazles %{name5}% &7(x1)
  msg6: &6Znalazles %{name6}% &7(x0)
